### ISSUE TITLE
Update Community Link in contact.html

### ISSUE THREAD

**Issue by ufraaan** [safwanishere/ResourceBase#1]
**Description:** The current link for the "Community" section in [**`contact.html`**](https://github.com/safwanishere/ResourceBase/blob/main/contact.html) points to YouTube. It needs to be updated to point to the WhatsApp community link.

**Current Code:**

```html
<a href="https://youtube.com"><h2>Community</h2></a>
```

**Required Change:** Update the link to the WhatsApp community URL:

```html
<a href="https://chat.whatsapp.com/InQyGpnanyuJYFfyTgMGaB"><h2>Community</h2></a>
```

**File to Modify:** [**`contact.html`**](https://github.com/safwanishere/ResourceBase/blob/main/contact.html)

**Reason for Change:** To ensure users are directed to the correct WhatsApp community.

**Comment by safwanishere** [comment]
Fixed the issue with commit 024fa1b
